name: pytorch-env
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - matplotlib
  - nb_conda_kernels
  - notebook
  - cpuonly
  - pytorch
  - torchvision
  - scikit-learn
  - pandas
  - tqdm
  - torchinfo

